### ISSUE TITLE
BlockRepairsInstead removing item on certain conditions

### ISSUE THREAD

**Issue by haeiven** [dniym/IllegalStack#10]
Hello,

The BlockRepairsInstead is removing the item when you put it in the anvil with a Shift click (Tested with item lores check in 1.14.4). It's removing the item only if the lore match.

Config:

>   ItemRemoval:
    ItemNamesToRemove: []
    ItemLoresToRemove: 
     - 'Durabilité'
    RemoveItemsMatchingName: false
    NameLoreStrictMatchMode: false
    BlockEnchantingInstead: false
    BlockRepairsInstead: true

Best regards,

**Comment by dniym** [comment]
RemoveItemsMatchingName: false   Should prevent the item from being removed.   Double check that the protection is actually off by doing:

/istack toggle RemoveItemsMatchingName

it should say if the protection is turned ON or OFF, remember if you ever edit the config manually, you MUST do /istack reload  otherwise the changes will not take effect.

**Comment by haeiven** [comment]
Hi,

Here's a video of my settings & the bug: https://youtu.be/Xpm-EZlnXwk

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
