### ISSUE TITLE
Serious issues

### ISSUE THREAD

**Issue by danil20028191** [dniym/IllegalStack#105]
It would be the best plugin to item fix if you add:
1. option to disable remove enchants/flags from other plugin gui menu (BetterGUI, DeluxeMenus)
2. add special enchant bypass for special items, even with custom names and lores, example: ENDER_EYE: PROTECTION,1 NAME:'&b&nAbilities' Lore:'&5right click(first line);&ato open menu(second line)' Then the enchantmet PROCETCION 1 woud not be removed from ENDER_EYE only with this properties.

**Comment by dniym** [comment]
1) unless the GUI plugin uses a custom inventory object it is quite difficult for IllegalStack to detect that it is a GUI.  Using the inventory name is not acceptable because players can name inventories. 

2) this feature already exists. https://github.com/dniym/IllegalStack/wiki/EnchantedItemWhiteList
