### ISSUE TITLE
Feature request: unstack illegal stacks instead of deleting them.

### ISSUE THREAD

**Issue by TheForgottenKing** [dniym/IllegalStack#161]
**Is your feature request related to a problem? Please describe.**
I would like a way to make it so overstacked items are simply unstacked instead of deleted.

**Describe the solution you'd like**
Current behavior for overstacked items results in the stack being deleted or set to the correct maximum value. I would like to have it where overstacked items are simply unstacked, with the resulting items either filling available slots in the players inventory or being dropped on the floor. For example, if someone had a stack of 64 diamond swords and an inventory with 14 slots available, IllegalStack would spread the 64 swords throughout their 14 inventory slots and drop the remaining 49 (64 items minus 14 slots minus 1 original sword slot) swords onto the floor. Same behavior with chests if possible but not as needed.

**Describe alternatives you've considered**
Current setup is just going to be giving all players a warning to unstack their items before I enable the stack removal check.

**Additional context**
n/a, thank you.

**Comment by dniym** [comment]
I know this response is late, but the reason IllegalStack does not unstack items is because if there is an exploit that allows players to dupe in items or create huge stacks then IllegalStack has no way of knowing if those items were "legitimately" overstacked.    Thus it is advisable to adhere to the vanilla stack limits because unstacking an illegally obtained stack of items would just hide the problem.
