### ISSUE TITLE
Players' Arrows and Tridents Despawning Mid Air

### ISSUE THREAD

**Issue by AlohaLegend** [dniym/IllegalStack#172]
Required Information

FAVS Version Number (/version IllegalStack): 1.9.5
Spigot/Paper Version Number (/version): 1.20.1
Output of /version: (Please provide the output of the command here)
Describe the bug
Arrows and tridents shot by players are despawning mid-air despite having all relevant configuration options set to false. This behavior is occurring in both the latest Paper 1.20.1 version and version 1.9.5 of IllegalStack.

To Reproduce

Install the latest Paper 1.20.1 and IllegalStack 1.9.5 versions on a server.
Ensure that all relevant configuration options in IllegalStack, related to arrow and trident behavior, are set to false.
Have a player shoot an arrow or throw a trident.
Observe that the arrow/trident despawns mid-air instead of behaving as expected.
Plugins being used on the server

Checklist:

 I included all information required in the sections above
 I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
 I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
 I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
This is due to the following protection, when this was written the despawn delay was initially set too short, you can correct this issue by increasing the ProjectileDespawnDelay.   

See this wiki page for info on the protection, you may disable it if you wish or adjust the despawn delay. 

https://github.com/dniym/IllegalStack/wiki/PreventProjectileExploit2
