### ISSUE TITLE
End portal

### ISSUE THREAD

**Issue by x1p** [dniym/IllegalStack#26]
When portal dupes is blocked, and `BlockNonPlayersInEndPortal: true` all dropped items are rejected. Which works awesome.

When the dragon exists, the portal is gone and the fountain is empty.
When the dragon is killed right above the fountain, and it drops (custom) loot. The loot falls into the empty fountain. After the ender dragon explodes, the fountain is recreated.
All dropped items that was in the empty fountain, disappears.

Is there a possibility to reject items laying on the bottom of the fountain when the portal is recreated?

**Comment by dniym** [comment]
Hmmm, this protection uses the event fired whenever an entity (in this case a dropped item) tries to enter a portal.   If the portal isn’t there then the check never occurs.  I’ll have to do some checking to see if when the portal is created there’s a way to teleport the items nearby so they don’t get stuck under it.

**Comment by dniym** [comment]
Sorry it's been so long since I responded about this topic.  I think i have come up with a way to clean out the portal.


If the dragon dies and is in the end, the plugin will search for the fountain, then launch any entities it finds inside it out for approx 30 seconds.   This should prevent anything from getting lost after the portal spawns.    Should be in the next update 2.1.2a+   There isn't an extra protection for this, if you have block entities from the end portal enabled it will take effect whenever the dragon gets killed.
