### ISSUE TITLE
[suggest] About StoppedPushableEntity

### ISSUE THREAD

**Issue by BackWheel** [dniym/IllegalStack#29]
When I trigger the StoppedPushableEntity event, it will cause the entity to disappear. This may cause losses to some players. Should the movement of the piston be prohibited? Instead of deleting the entity?

**Comment by dniym** [comment]
In the misc section of config.yml there is an option to drop the items rather than just removing them.    Removing them is intended to be a deterrent to keep people from trying over and over with a particular exploit. 

BreakMachinesInsteadOfDroppingItems: true 

#If this setting is set to FALSE, instead of removing pistons etc that are detected in an exploit, IllegalStack will break the block and drop the item instead.


This should resolve this issue, if so please come back and close it! :)

**Comment by BackWheel** [comment]
I just tried some, although I turned off this option, but when I use the piston to push the armor stand, it still makes the armor stand disappear, but it seems that there is no such problem for other entities such as mine cars.

**Comment by dniym** [comment]
Alright, I will do some testing on my end when I get home and sort this out.

**Comment by BackWheel** [comment]
Thanks

**Comment by dniym** [comment]
This is reasonably difficult to do still looking for a solution, tried just killing the armor stand via the plugin and damaging it and it does not seem to want to die and drop the items.

**Comment by dniym** [comment]
Still no luck fixing this, You may want to switch this protection off if it is still causing you issues.
