### ISSUE TITLE
water buckets problem!

### ISSUE THREAD

**Issue by Alekhedjran** [dniym/IllegalStack#50]
Players cant have more than 1 water bucket in inv or it takes ti away! How do i fix this?

**Comment by dniym** [comment]
I assume they’re getting removed if they have multiple water buckets stacked together.  This is because Minecraft sets a limit of 1 to filled buckets (lava/water/milk) you can whitelist these items if you wish for players to be able to overstack them with the following command: 

: /istack value add AllowStack (ITEM_TYPE)
